config/routes.rb
Rails.application.routes.draw do
  resources :foods
  root 'foods#index'
 end

app/models/food.rb
class Food < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :edit, :update, :destroy]

def index
  @foods = Food.all.order('created_at DESC')
  end

def show
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(foods_params)

    if @food.save
      redirect_to @food
    else
      render "New"
  end
end

  def edit
  end

  def update
    @food = Food.update(foods_params)

    if @food.update
      redirect_to @food
    else
      render "Edit"
  end
end

  def destroy
    @food.destroy
    redirect_to root_path
  end

  private

  def foods_params
    params.require(:food).permit(:title, :description, :company, :rating, :url)
  end

  def find_food
    @food = Food.find(params[:id])
   end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.haml
= simple_form_for(@food, html: { class: 'form-horizontal'}) do |f|
  = f.input :title, label: "Food name"
  = f.input :description, label: "Food Description"
  = f.input :company, label: "Your Company"
  = f.input :rating, label: "Your Rating"
  = f.input :url, label: "Link to Food"
  %br/
  = f.button :submit

app/views/foods/edit.html.haml
%h1 Edit Food

= render 'form'

= link_to "Back", root_path

app/views/foods/index.html.haml
= @foods.each do |food|
  %h2= link_to food.title, food
  %p= food.company

  = link_to "New Food", new_food_path

app/views/foods/new.html.haml
%h1 New Food

= render 'form'

= link_to "Back", root_path

app/views/foods/show.html.haml
%h1= @food.title
%p= @food.description
%p= @food.company
%p= @food.rating

= link_to "Home", root_path
= link_to "Edit", edit_food_path(@food)
= link_to "Delete", food_path(@food), method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>